/*
 http://www.gnu.org/licenses/gpl-3.0.txt GPL
*/
try{document.execCommand("BackgroundImageCache",true,true)}catch(err){}window.__noconflict&&jQuery.noConflict();
(function(a){function e(b){var c=a("<div></div>").attr("id","activebar-container");c.css({display:"none",position:"fixed",zIndex:"9999",top:"0px",left:"0px",cursor:"default",padding:"4px","font-size":"9px",background:b.background,borderBottom:"1px solid "+b.border,color:b.fontColor});a(window).bind("resize",function(){c.width(a(this).width())});a(window).trigger("resize");if(a.browser.msie&&(a.browser.version.substring(0,1)=="5"||a.browser.version.substring(0,1)=="6")){c.css("position","absolute");
a(window).scroll(function(){c.stop(true,true);a.fn.activebar.state==3?c.css("top",a(window).scrollTop()+"px"):c.css("top",a(window).scrollTop()-c.height()+"px")}).resize(function(){a(window).scroll()})}c.append(a("<div></div>").attr("class","icon").css({"float":"left",width:"16px",height:"16px",margin:"0 4px 0 0",padding:"0"}).append('<img src="'+b.icons_path+'icon.png" class="normal">').append('<img src="'+b.icons_path+'icon-over.png" class="hover">'));c.append(a("<div></div>").attr("class","close").css({"float":"right",
margin:"0 5px 0 0 ",width:"16px",height:"16px"}).click(function(d){a.fn.activebar.hide();d.stopPropagation();a.cookie("ie6update","closed")}).append('<img src="'+b.icons_path+'close.png" class="normal">').append('<img src="'+b.icons_path+'close-over.png" class="hover">'));c.append(a("<div></div>").attr("class","content").css({margin:"0px 8px",paddingTop:"1px"}));a(".hover",c).hide();a("body").prepend(c);return c}function f(b,c){b.unbind("mouseenter mouseleave");b.hover(function(){a(this).css({backgroundColor:c.highlight,
color:"#FFFFFF"}).addClass("hover");a(".hover",b).show();a(".normal",b).hide()},function(){a(this).css({backgroundColor:c.background,color:"#000000"}).removeClass("hover");a(".hover",b).hide();a(".normal",b).show()});a(".content",b).css({fontFamily:c.font,fontSize:c.fontSize})}a.fn.activebar=function(b){b=a.fn.extend({},a.fn.activebar.defaults,b);if(a.fn.activebar.container===null)a.fn.activebar.container=e(b);f(a.fn.activebar.container,b);a.fn.activebar.hide();a(".content",a.fn.activebar.container).empty();
a(this).each(function(){a(".content",a.fn.activebar.container).append(this)});a.fn.activebar.container.unbind("click");b.url!==null&&a.fn.activebar.container.click(function(){window.location.href=b.url});a.fn.activebar.container.css("top","-"+a.fn.activebar.container.height()+"px");if(b.preload){var c={a:0,b:0,c:0,d:0},d=function(){c.a&&c.b&&c.c&&c.d&&a.fn.activebar.show()};a('<img src="'+b.icons_path+'icon.png" class="normal">').load(function(){c.a=1;d()});a('<img src="'+b.icons_path+'icon-over.png" class="normal">').load(function(){c.b=
1;d()});a('<img src="'+b.icons_path+'close.png" class="normal">').load(function(){c.c=1;d()});a('<img src="'+b.icons_path+'close-over.png" class="normal">').load(function(){c.d=1;d()})}else a.fn.activebar.show()};a.fn.activebar.defaults={background:"#ffffe1",border:"#666",highlight:"#3399ff",font:"Bitstream Vera Sans,verdana,sans-serif",fontColor:"InfoText",fontSize:"11px",icons_path:"images/",url:"http://www.microsoft.com/windows/internet-explorer/default.aspx",preload:true};a.fn.activebar.state=
0;a.fn.activebar.container=null;a.fn.activebar.show=function(){if(!(a.fn.activebar.state>1)){a.fn.activebar.state=2;a.fn.activebar.container.css("display","block");var b=a.fn.activebar.container.height();a.fn.activebar.container.animate({top:"+="+b+"px"},b*20,"linear",function(){a.fn.activebar.state=3})}};a.fn.activebar.hide=function(){if(!(a.fn.activebar.state<2)){a.fn.activebar.state=1;var b=a.fn.activebar.container.height();a.fn.activebar.container.animate({top:"-="+b+"px"},b*20,"linear",function(){a.fn.activebar.container.css("display",
"none");a.fn.activebar.visible=false})}}})(jQuery);jQuery(document).ready(function(a){a("<div></div>").html(IE6UPDATE_OPTIONS.message||"Internet Explorer is missing updates required to view this site. Click here to update... ").activebar(window.IE6UPDATE_OPTIONS)});
