jQuery(function(f){f.fn.fcbkcomplete=function(I){return this.each(function(){function J(){K();L();A(0)}function K(){l.hide();l.attr("multiple","multiple");l.attr("name").indexOf("[]")==-1&&l.attr("name",l.attr("name")+"[]");m=f(document.createElement("ul"));m.attr("class","holder");l.after(m);k=f(document.createElement("div"));k.addClass("facebook-auto");k.append('<div class="default">'+g.complete_text+"</div>");if(p){k.append('<iframe class="ie6fix" scrolling="no" frameborder="0"></iframe>');q=k.children(".ie6fix")}b=
f(document.createElement("ul"));b.attr("id",u+"_feed");k.prepend(b);m.after(k);b.css("width",k.width())}function L(){l.children("option").each(function(d,a){a=f(a);if(a.hasClass("selected")){s(a.text(),a.val(),true);a.attr("selected","selected")}else a.removeAttr("selected");o.push({caption:a.text(),value:a.val()});t+=""+(o.length-1)+":"+a.text()+";"})}function s(d,a,c){var h=document.createElement("li"),j=document.createTextNode(d),r=document.createElement("a");f(h).attr({"class":"bit-box",rel:a});
f(h).prepend(j);f(r).attr({"class":"closebutton",href:"#"});h.appendChild(r);m.append(h);f(r).click(function(){f(this).parent("li").fadeOut("fast",function(){B(f(this))});return false});if(!c){f("#"+u+"_annoninput").remove();var n;A(1);if(l.children("option[value="+a+"]").length){n=l.children("option[value="+a+"]");n.get(0).setAttribute("selected","selected");n.hasClass("selected")||n.addClass("selected")}else{n=f(document.createElement("option"));n.attr("value",a).get(0).setAttribute("selected",
"selected");n.attr("value",a).addClass("selected");n.text(d);l.append(n)}g.onselect.length&&C(g.onselect,n)}m.children("li.bit-box.deleted").removeClass("deleted");b.hide();p&&q.hide()}function B(d){if(g.onremove.length){var a=l.children("option[value="+d.attr("rel")+"]");C(g.onremove,a)}l.children("option[value="+d.attr("rel")+"]").removeAttr("selected");l.children("option[value="+d.attr("rel")+"]").removeClass("selected");d.remove();w=0}function A(d){var a=f(document.createElement("li")),c=f(document.createElement("input"));
a.attr({"class":"bit-input",id:u+"_annoninput"});c.attr({type:"text","class":"maininput",size:"1"});m.append(a.append(c));c.focus(function(){k.fadeIn("fast")});c.blur(function(){k.fadeOut("fast")});m.click(function(){c.focus();if(b.length&&c.val().length)b.show();else{b.hide();p&&q.hide();k.children(".default").show()}});c.keypress(function(h){if(h.keyCode==13)return false;c.attr("size",c.val().length+1)});c.keydown(function(h){if(h.keyCode==191){h.preventDefault();return false}});c.keyup(function(h){var j=
D(c.val());if(h.keyCode==8&&j.length==0){b.hide();p&&q.hide();if(m.children("li.bit-box.deleted").length==0){m.children("li.bit-box:last").addClass("deleted");return false}else{if(w)return;w=1;m.children("li.bit-box.deleted").fadeOut("fast",function(){B(f(this));return false})}}if(h.keyCode!=40&&h.keyCode!=38&&j.length!=0){v=0;if(g.json_url)if(g.cache&&E){x(j);y()}else f.getJSON(g.json_url+"?tag="+j,null,function(r){x(j,r);E=true;y()});else{x(j);y()}k.children(".default").hide();b.show()}});d&&setTimeout(function(){c.focus();
k.children(".default").show()},1)}function x(d,a){b.html("");if(!g.cache){o=[];t=""}M(d);a!=null&&a.length&&f.each(a,function(n,z){o.push({caption:z.caption,value:z.value});t+=""+(o.length-1)+":"+z.caption+";"});a=g.maxshownitems<o.length?g.maxshownitems:o.length;var c="i";if(g.filter_case)c="";var h,j;try{h=eval("/(?:^|;)\\s*(\\d+)\\s*:[^;]*?"+d+"[^;]*/g"+c);j=h.exec(t)}catch(r){}for(c="";j!=null&&a>0;){j=j[1];j=o[j];if(!(g.filter_selected&&l.children("option[value="+j.value+"]").hasClass("selected"))){c+=
'<li rel="'+j.value+'">'+N(j.caption,d)+"</li>";v++;a--}j=h.exec(t)}b.append(c);if(g.firstselected){e=b.children("li:visible:first");e.addClass("auto-focus")}if(v>g.height){b.css({height:g.height*24+"px",overflow:"auto"});p&&q.css({height:g.height*24+"px",width:b.width()+"px"}).show()}else{b.css("height","auto");p&&q.css({height:b.height()+"px",width:b.width()+"px"}).show()}}function N(d,a){if(g.filter_case)try{eval("var text = text.replace(/(.*)("+a+")(.*)/gi,'$1<em>$2</em>$3');")}catch(c){}else try{eval("var text = text.replace(/(.*)("+
a.toLowerCase()+")(.*)/gi,'$1<em>$2</em>$3');")}catch(h){}return d}function F(){b.children("li").mouseover(function(){b.children("li").removeClass("auto-focus");f(this).addClass("auto-focus");e=f(this)});b.children("li").mouseout(function(){f(this).removeClass("auto-focus");e=null})}function G(){b.children("li").unbind("mouseover");b.children("li").unbind("mouseout");b.mousemove(function(){F();b.unbind("mousemove")})}function y(){var d=f("#"+u+"_annoninput").children(".maininput");F();b.children("li").unbind("mousedown");
b.children("li").mousedown(function(){var a=f(this);s(a.text(),a.attr("rel"));b.hide();p&&q.hide();k.hide()});d.unbind("keydown");d.keydown(function(a){if(a.keyCode==191){a.preventDefault();return false}a.keyCode!=8&&m.children("li.bit-box.deleted").removeClass("deleted");if(a.keyCode==13&&H()){var c=e;s(c.text(),c.attr("rel"));k.hide();a.preventDefault();e=null;return false}if(a.keyCode==13&&!H()){if(g.newel){c=D(f(this).val());s(c,c);k.hide();a.preventDefault();e=null}return false}if(a.keyCode==
40){G();if(e==null||e.length==0){e=b.children("li:visible:first");b.get(0).scrollTop=0}else{e.removeClass("auto-focus");e=e.nextAll("li:visible:first");c=parseInt(e.prevAll("li:visible").length,10);var h=parseInt(e.nextAll("li:visible").length,10);if((c>Math.round(g.height/2)||h<=Math.round(g.height/2))&&typeof e.get(0)!="undefined")b.get(0).scrollTop=parseInt(e.get(0).scrollHeight,10)*(c-Math.round(g.height/2))}b.children("li").removeClass("auto-focus");e.addClass("auto-focus")}if(a.keyCode==38){G();
if(e==null||e.length==0){e=b.children("li:visible:last");b.get(0).scrollTop=parseInt(e.get(0).scrollHeight,10)*(parseInt(b.children("li:visible").length,10)-Math.round(g.height/2))}else{e.removeClass("auto-focus");e=e.prevAll("li:visible:first");c=parseInt(e.prevAll("li:visible").length,10);h=parseInt(e.nextAll("li:visible").length,10);if((h>Math.round(g.height/2)||c<=Math.round(g.height/2))&&typeof e.get(0)!="undefined")b.get(0).scrollTop=parseInt(e.get(0).scrollHeight,10)*(c-Math.round(g.height/
2))}b.children("li").removeClass("auto-focus");e.addClass("auto-focus")}})}function M(d){if(g.newel){b.children("li[fckb=1]").remove();if(d.length!=0){var a=f(document.createElement("li"));a.attr({rel:d,fckb:"1"}).html(d);b.prepend(a);v++}}}function C(d,a){var c="";for(i=0;i<a.get(0).attributes.length;i++)if(a.get(0).attributes[i].nodeValue!=null)c+='"_'+a.get(0).attributes[i].nodeName+'": "'+a.get(0).attributes[i].nodeValue+'",';c="{"+c+" notinuse: 0}";try{eval(d+"("+c+")")}catch(h){}}function H(){if(e==
null)return false;if(e.length==0)return false;return true}function D(d){d=d.replace(/[\"\'][\s]*javascript:(.*)[\"\']/g,'""');d=d.replace(/script(.*)/g,"");d=d.replace(/eval\((.*)\)/g,"");return d=d.replace("/([\u0000-\u0008,\u000b-\u000c,\u000e-\u0019])/","")}this.addItem=function(d,a){s(d,a)};var g=f.extend({json_url:null,cache:false,height:"10",newel:false,firstselected:false,filter_case:false,filter_hide:false,complete_text:"Start to type...",maxshownitems:30,onselect:"",onremove:""},I),m=null,
b=null,k=null,v=0,o=[],E=false,t="",e=null,w=0,p=false,q,l=f(this),u=l.attr("id");J();return this})}});
